test_closest (__main__.TestExercice) ... ok
<<<<<<< HEAD
test_coordinates (__main__.TestExercice) ... ok
test_linear_values (__main__.TestExercice) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.001s

OK
=======
test_coordinates (__main__.TestExercice) ... FAIL
test_linear_values (__main__.TestExercice) ... ok

======================================================================
FAIL: test_coordinates (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 29, in test_coordinates
    np.testing.assert_array_equal(
  File "/home/runner/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 934, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/runner/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 763, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
Mauvaise rÃ©ponse
(shapes (2,), (3, 2) mismatch)
 x: array([14.317821063276353, array([1.57079633, 1.57079633])], dtype=object)
 y: array([[ 0.      ,  0.      ],
       [14.142136,  0.785398],
       [ 2.236068, -0.463648]])

----------------------------------------------------------------------
Ran 3 tests in 0.003s

FAILED (failures=1)
>>>>>>> dec190267b18ee328a68d06d3dfcacfeabe36506
